### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by MadSoeDK** [commandiron/SpinWheelCompose#2]
I think some of the default behaviour is not obvious without looking through the code:

- When not providing resultDegree, the spin should be random
- When not providing autoResetDelay, the spinner should not reset.

**Comment by commandiron** [comment]
I will try to implement your suggestions as soon as possible, thank you.

**Comment by commandiron** [comment]
hey meds with the [new version](https://github.com/commandiron/SpinWheelCompose/releases/tag/1.1.0) I solved the problems here and made the code more readable and logical. If you get a chance to try it, I look forward to your feedback. I wish you good work.
